version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8000/healthz/"]
      interval: 30s
      retries: 3
